quarkus.application.name=FatigoonAPI

# --- Datasource ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=shawn
quarkus.datasource.password=j28
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/FatigoonDB

# --- Hibernate ORM ---
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=drop-and-create

# --- Logging ---
quarkus.log.level=INFO
quarkus.log.console.enabled=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

# --- Configuration Gemini ---
quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY}
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-2.5-flash

quarkus.langchain4j.ai.gemini.timeout=60s
quarkus.langchain4j.ai.gemini.log-requests=true
quarkus.langchain4j.ai.gemini.log-responses=true
quarkus.vertx.max-event-loop-execute-time=5s