# --- Datasource ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=shawn
quarkus.datasource.password=j28
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/FatigoonDB

# --- Hibernate ORM ---
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=drop-and-create

# --- Logging ---
quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

quarkus.application.name=FatigoonAPI
